### Group By

In [8]:
import numpy as np
import pandas as pd
from IPython.display import display
students=pd.read_csv('data\student-dataset.csv')
#group data
gender_data=students.groupby('gender')
display(gender_data)
display(gender_data.count())

gender_data['english.grade'].mean()
group_by_nationality=students.groupby('nationality')
display(group_by_nationality['math.grade'].mean())

<>:4: SyntaxWarning: invalid escape sequence '\s'
<>:4: SyntaxWarning: invalid escape sequence '\s'
C:\Users\sandh\AppData\Local\Temp\ipykernel_8232\2369614814.py:4: SyntaxWarning: invalid escape sequence '\s'
  students=pd.read_csv('data\student-dataset.csv')


id  name  nationality  city  latitude  longitude  ethnic.group  age  \
gender                                                                         
F       152   152          152   152       152        152             0  152   
M       151   151          151   151       151        151             0  151   
other     4     4            4     4         4          4             0    4   

        english.grade  math.grade  sciences.grade  language.grade  \
gender                                                              
F                 152         152             152             152   
M                 151         151             151             151   
other               4           4               4               4   

        portfolio.rating  coverletter.rating  refletter.rating  
gender                                                          
F                    152                 152               152  
M                    151                 151               151  
other                  4                   4                 4

nationality
Bangladesh                  3.900000
Brazil                      3.377778
Canada                      3.014286
Chile                       3.700000
China                       3.784615
Colombia                    3.580000
Cuba                        2.800000
Dominican Republic          3.800000
Egypt                       3.500000
El Salvador                 2.900000
Germany                     3.500000
India                       3.275000
Japan                       3.538462
Korea (Republic of)         3.066667
Mexico                      3.387500
Morocco                     3.600000
Myanmar                     3.400000
Netherlands                 3.500000
Nicaragua                   3.700000
Pakistan                    2.933333
Peru                        3.100000
Philippines                 3.600000
Poland                      3.800000
Russian Federation          3.383333
Spain                       3.750000
Thailand                    3.900000
Tunisia                   

### Aggregration
- count()-
- Sum()
- min()
- max()

### Sorting
## SOrt by Index
## Sort by Value
- Ascending:true
- Descending:false
- Sorting by Date
- Sorting with key Function

In [10]:
students=pd.read_csv('data\student-dataset.csv')
# //ascending false: z-a
new_sort=students.sort_values(by=['name','math.grade'],ascending=False) 
display(new_sort)

#sort by math grade
students.sort_values(by='math.grade',ascending=False, inplace=True)
students

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\sandh\AppData\Local\Temp\ipykernel_8232\1292632512.py:1: SyntaxWarning: invalid escape sequence '\s'
  students=pd.read_csv('data\student-dataset.csv')


id                    name               nationality         city  \
47    47                Zoe Kern  United States of America  West Jordan   
175  175       Zahraaa el-Yousef                     India       Hospet   
259  259       Zaghlool al-Pasha                     India       Deoria   
304  304       Zachary Mulvahill  United States of America  Los Angeles   
52    52         Zachary Bradley                     Spain       Madrid   
..   ...                     ...                       ...          ...   
250  250         Abigail Orgeron  United States of America   Prior Lake   
226  226        Abigail Gallegos                    Brazil        Belém   
150  150  Abdul Jabbaar el-Abdul                     Egypt        Cairo   
204  204             Aaron Knott  United States of America    Santa Ana   
172  172        Aaqil el-Hashemi                     India    Bangalore   

     latitude  longitude gender  ethnic.group  age  english.grade  math.grade  \
47      40.61    -111.94      F           NaN   22            2.1         4.0   
175     15.27      76.40      F           NaN   22            3.9         3.7   
259     26.50      83.79      M           NaN   21            2.3         3.8   
304     34.05    -118.24      M           NaN   20            3.2         3.4   
52      40.41      -3.69      M           NaN   21            3.5         3.5   
..        ...        ...    ...           ...  ...            ...         ...   
250     44.71     -93.42      F           NaN   23            3.2         3.0   
226     -1.45     -48.48      F           NaN   24            3.4         3.0   
150     30.05      31.25      M           NaN   20            1.5         3.5   
204     33.75    -117.87      M           NaN   23            3.2         3.6   
172     12.98      77.58      M           NaN   21            3.4         3.0   

     sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
47              3.4             5.0                 4                 5.0   
175             3.8             4.0                 4                 4.0   
259             3.8             4.0                 5                 5.0   
304             3.9             5.0                 5                 5.0   
52              3.4             2.0                 3                 5.0   
..              ...             ...               ...                 ...   
250             3.8             5.0                 5                 5.0   
226             2.1             4.0                 3                 3.0   
150             3.2             3.0                 3                 5.0   
204             3.7             5.0                 4                 5.0   
172             3.6             3.0                 5                 5.0   

     refletter.rating  
47                  4  
175                 4  
259                 5  
304                 3  
52                  5  
..                ...  
250                 4  
226                 4  
150                 4  
204                 4  
172                 4  

[307 rows x 16 columns]

id                  name               nationality               city  \
37    37         Katrina Saito                     Japan              Tokyo   
11    11          Sasha Jansen  United States of America            Chicago   
286  286       Michael Griffin  United States of America           New York   
182  182     Billy Jack Bestle  United States of America          Baltimore   
129  129        Coleman Keelen                     Spain  Callosa de Segura   
..   ...                   ...                       ...                ...   
73    73  Aurelia Davis Ingham  United States of America          Roseville   
133  133          Andrew Kirin  United States of America             Odessa   
59    59      Shuraih el-Karim                  Pakistan           Khalabat   
288  288      Weldon Hightower  United States of America           New York   
272  272       William Tierney  United States of America           New York   

     latitude  longitude gender  ethnic.group  age  english.grade  math.grade  \
37      35.69     139.75      F           NaN   22            3.8         4.0   
11      41.85     -87.65      F           NaN   21            1.7         4.0   
286     40.71     -74.01      M           NaN   21            4.0         4.0   
182     39.29     -76.61      M           NaN   22            3.7         4.0   
129     38.12      -0.88      M           NaN   24            3.4         4.0   
..        ...        ...    ...           ...  ...            ...         ...   
73      38.75    -121.29      F           NaN   22            3.8         2.2   
133     31.85    -102.37      M           NaN   25            3.8         2.2   
59      34.06      72.89      M           NaN   22            3.1         2.1   
288     40.71     -74.01      M           NaN   20            2.6         2.1   
272     40.71     -74.01      M           NaN   21            3.8         2.1   

     sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
37              3.7             4.0                 5                 4.0   
11              3.6             5.0                 4                 4.0   
286             4.0             5.0                 3                 5.0   
182             3.8             5.0                 5                 4.0   
129             3.4             4.0                 4                 4.0   
..              ...             ...               ...                 ...   
73              3.7             5.0                 4                 5.0   
133             3.0             5.0                 3                 2.0   
59              2.3             4.0                 4                 4.0   
288             3.2             5.0                 4                 5.0   
272             3.0             5.0                 3                 4.0   

     refletter.rating  
37                  5  
11                  5  
286                 5  
182                 5  
129                 4  
..                ...  
73                  5  
133                 3  
59                  4  
288                 5  
272                 4  

[307 rows x 16 columns]

In [11]:
data=pd.read_csv('data\student-admission.csv')
#convert to datetime
data['AdmissionDate']=pd.to_datetime(data['AdmissionDate'])
#sort by admission date
students.sort_values(by='math.grade',ascending=False,inplace=True)
students.head()



<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\sandh\AppData\Local\Temp\ipykernel_8232\3937621900.py:1: SyntaxWarning: invalid escape sequence '\s'
  data=pd.read_csv('data\student-admission.csv')


id                 name               nationality       city  latitude  \
37    37        Katrina Saito                     Japan      Tokyo     35.69   
290  290  Michaela Schoenbeck  United States of America    Rexburg     43.83   
11    11         Sasha Jansen  United States of America    Chicago     41.85   
183  183    Isabella Martinez                  Colombia     Bogotá      4.65   
294  294       Matthew Obourn  United States of America  San Diego     32.72   

     longitude gender  ethnic.group  age  english.grade  math.grade  \
37      139.75      F           NaN   22            3.8         4.0   
290    -111.79      F           NaN   22            3.9         4.0   
11      -87.65      F           NaN   21            1.7         4.0   
183     -74.06      F           NaN   23            2.6         4.0   
294    -117.16      M           NaN   23            3.9         4.0   

     sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
37              3.7             4.0                 5                 4.0   
290             3.3             5.0                 5                 4.0   
11              3.6             5.0                 4                 4.0   
183             2.7             4.0                 3                 4.0   
294             3.9             5.0                 4                 4.0   

     refletter.rating  
37                  5  
290                 4  
11                  5  
183                 3  
294                 4

## Slicing in NUmpy
- to print multiple subset, numpy is done
- we can access the portion of an array

In [6]:
#one dimension array
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,10,11])
print(arr[2:6])#[3,4,5,6]

#2 dimensional array
print(arr[0:8:2]) # start,stop,step
print(arr[4:])# last data starting from 4
print(arr[:3])

[3 4 5 6]
[1 3 5 7]
[ 5  6  7  8 10 11]
[1 2 3]


## 2D Slicing
- syantax:array[row_start:row_stop:row_step,col_start:col_stop:col_step]

In [8]:
array_2d=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(array_2d.ndim)

2
