## Numpy
- collection of high level  mathematical functional operation
- matrix: two dimensional data
- numerical python


## Feature of NUMpy
- A powerful N-dimensional array object
- Sophisticated (broadcasting function)
- Tools for integration c/c++ and fortran code

## Dif bet numpy and python list
- numpyarry:fast program (memory use once
), store variable in stack i.e 1,2,3,4 (data type phaila nai tha hunxa, no need to def data type)
- python list:slow(item define) to use 1.meta data i.e int, string 2. actual value arko thauma use hunxa


## From Python List, Tuple

In [2]:
import numpy as np
from IPython.display import display
#calc only number
np_array=np.array([2,3,4,5,6])
display(np_array)
np_array_tuple=np.array((1,3,4,5)) # tuple
display(np_array_tuple)
display(type(np_array))
display(np_array.shape)
display(np_array.dtype)


array([2, 3, 4, 5, 6])

array([1, 3, 4, 5])

numpy.ndarray

(5,)

dtype('int32')

## Create array with default values
- create an array with zero np.zeros((2,2))
- create array filled with ones((2,2))
- create an array filled with a specific value np.full((2,2),3)

In [3]:
zero_array=np.zeros((2,2)) # create n=2 m=2 array filled with zeros
print(zero_array)
ones_array=np.ones((3,4))
print(ones_array)
fill_array=np.full((2,3),3)
print(fill_array)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3 3 3]
 [3 3 3]]


# creatung array with ranges of values
- np.array (0,25,5) #[0,5,10,15,20]
- np.linespace(0,100,1000)

In [9]:
np_arrange=np.arange(0,25,1)
print(np_arrange)
np_linespace=np.linspace(0,100,11) # create evenly space 11-1 points from 0-100
print(np_linespace)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [8]:
identical_array=np.eye(3,3)
print(identical_array)
diagonal_array=np.diag([1,2,3])
print(diagonal_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Random Array
- np.random.rand([3,3] create 3 x 3)

In [11]:
import matplotlib.pyplot as plt
random_array=np.random.rand(3,3)
print(random_array)

rand_in_bet=np.random.randint(1,100,(3,3))
print(rand_in_bet)
random_choice=np.random.choice([1,2,4,5,9,10],size=(3,3))
print(random_choice)

[[0.39044714 0.24014247 0.31874418]
 [0.5522387  0.26616518 0.45631928]
 [0.51764133 0.2204667  0.52296565]]
[[76 64 80]
 [88 25 58]
 [44 97 58]]
[[ 5 10  4]
 [ 5 10  9]
 [10  1  5]]


## Normal Distribution
- data collect show in bell shape curve

In [13]:
#draw histogram from normal distribution
mu,sigma=0,0.1 #mean and standard deviation
rand_array_normal_distro=np.random.normal(mu,sigma,1000) # normal distribution
count,bins,ignored= plt.hist(rand_array_normal_distro,30,density=True)
plt.plot(bins,1/(sigma * np.sqrt(2 * np.pi))* np.exp(-(bins-mu)**2/(2* sigma**2)),linewidth=2,color='r')
plt.show()

## Reshaping Array using Reshape method
- Reshape array of size(m,n)to(m1,m2)

In [14]:
import numpy as np
# Reshaping 1,6,array to 2 x3 array
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(2,3)
print("Original array:\n",arr)
print("Reshape array:\n",newarr)

Original array:
 [1 2 3 4 5 6]
Reshape array:
 [[1 2 3]
 [4 5 6]]


In [15]:
#flatten array
arr=np.array([
    [1,2,3],
    [4,5,6]
])
flat_arr=arr.flatten()
print("Original array:\n",arr)
print("Fattened array:\n",flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


# Numpy Array Indexing and Slicing
- Basic Indexing
    - Indexing allow us to access the individual element or subsets of data

In [22]:
# 1dimension Array
arr=np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr[0])
print(arr[-1])
print(arr[3])

# 2 dimension array
num_2d_array=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(num_2d_array.shape)
print(num_2d_array.ndim) # print dimension of array
print(num_2d_array.size)# print total number of items

print(num_2d_array[0,0])# first row first element =>1
print(num_2d_array[-1,-1])# first row last element =>8
print(num_2d_array[1,2])# second row third element =>6

(6,)
1
6
4
(3, 3)
2
9
1
9
6
